---
- name: webserver package installation
  hosts: 10.128.0.6
  tasks: 
   - name: Installing httpd package
     yum:
      name: httpd
      state: latest
   - name: Starting the httpd service
     service: 
      name: httpd
      state: restarted
...
